language: python
python:
  - 2.7
  - 3.5
  - 3.6

install:
  - pip install -e .
  - python setup.py install
  - pip install pytest coverage pytest-cov flake8

script:
  - py.test --cov=aston aston
  - flake8 aston
