# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './aston/qtgui/ui/ui_filterwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_filterDialog(object):
    def setupUi(self, filterDialog):
        filterDialog.setObjectName("filterDialog")
        filterDialog.resize(500, 450)
        self.verticalLayout = QtWidgets.QVBoxLayout(filterDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ionBox = QtWidgets.QGroupBox(filterDialog)
        self.ionBox.setFlat(False)
        self.ionBox.setCheckable(False)
        self.ionBox.setChecked(False)
        self.ionBox.setObjectName("ionBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ionBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ionList = QtWidgets.QListWidget(self.ionBox)
        self.ionList.setObjectName("ionList")
        self.verticalLayout_2.addWidget(self.ionList)
        self.addIonsTabWidget = QtWidgets.QTabWidget(self.ionBox)
        self.addIonsTabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.addIonsTabWidget.setDocumentMode(True)
        self.addIonsTabWidget.setObjectName("addIonsTabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.definedIonBox = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.definedIonBox.sizePolicy().hasHeightForWidth())
        self.definedIonBox.setSizePolicy(sizePolicy)
        self.definedIonBox.setObjectName("definedIonBox")
        self.horizontalLayout_4.addWidget(self.definedIonBox)
        self.addDefinedIonButton = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addDefinedIonButton.sizePolicy().hasHeightForWidth())
        self.addDefinedIonButton.setSizePolicy(sizePolicy)
        self.addDefinedIonButton.setObjectName("addDefinedIonButton")
        self.horizontalLayout_4.addWidget(self.addDefinedIonButton)
        self.addIonsTabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.singleIonBox = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.singleIonBox.sizePolicy().hasHeightForWidth())
        self.singleIonBox.setSizePolicy(sizePolicy)
        self.singleIonBox.setEditable(True)
        self.singleIonBox.setObjectName("singleIonBox")
        self.horizontalLayout_2.addWidget(self.singleIonBox)
        self.addSingleIonButton = QtWidgets.QPushButton(self.tab_2)
        self.addSingleIonButton.setObjectName("addSingleIonButton")
        self.horizontalLayout_2.addWidget(self.addSingleIonButton)
        self.addIonsTabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.startRangeIonBox = QtWidgets.QSpinBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startRangeIonBox.sizePolicy().hasHeightForWidth())
        self.startRangeIonBox.setSizePolicy(sizePolicy)
        self.startRangeIonBox.setObjectName("startRangeIonBox")
        self.horizontalLayout_3.addWidget(self.startRangeIonBox)
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setMaximumSize(QtCore.QSize(20, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(False)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.endRangeIonBox = QtWidgets.QSpinBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endRangeIonBox.sizePolicy().hasHeightForWidth())
        self.endRangeIonBox.setSizePolicy(sizePolicy)
        self.endRangeIonBox.setObjectName("endRangeIonBox")
        self.horizontalLayout_3.addWidget(self.endRangeIonBox)
        self.addRangeIonButton = QtWidgets.QPushButton(self.tab_3)
        self.addRangeIonButton.setObjectName("addRangeIonButton")
        self.horizontalLayout_3.addWidget(self.addRangeIonButton)
        self.addIonsTabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.userIonBox = QtWidgets.QLineEdit(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userIonBox.sizePolicy().hasHeightForWidth())
        self.userIonBox.setSizePolicy(sizePolicy)
        self.userIonBox.setObjectName("userIonBox")
        self.horizontalLayout.addWidget(self.userIonBox)
        self.addUserIonButton = QtWidgets.QPushButton(self.tab_4)
        self.addUserIonButton.setObjectName("addUserIonButton")
        self.horizontalLayout.addWidget(self.addUserIonButton)
        self.addIonsTabWidget.addTab(self.tab_4, "")
        self.verticalLayout_2.addWidget(self.addIonsTabWidget)
        self.verticalLayout.addWidget(self.ionBox)
        self.offsetBox = QtWidgets.QGroupBox(filterDialog)
        self.offsetBox.setCheckable(True)
        self.offsetBox.setChecked(False)
        self.offsetBox.setObjectName("offsetBox")
        self.gridLayout = QtWidgets.QGridLayout(self.offsetBox)
        self.gridLayout.setObjectName("gridLayout")
        self.XOffsetBox = QtWidgets.QDoubleSpinBox(self.offsetBox)
        self.XOffsetBox.setMinimum(-1000.0)
        self.XOffsetBox.setMaximum(1000.0)
        self.XOffsetBox.setObjectName("XOffsetBox")
        self.gridLayout.addWidget(self.XOffsetBox, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.offsetBox)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.YOffsetBox = QtWidgets.QDoubleSpinBox(self.offsetBox)
        self.YOffsetBox.setMinimum(-10000.0)
        self.YOffsetBox.setMaximum(10000.0)
        self.YOffsetBox.setObjectName("YOffsetBox")
        self.gridLayout.addWidget(self.YOffsetBox, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.offsetBox)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.offsetBox)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.YScaleBox = QtWidgets.QDoubleSpinBox(self.offsetBox)
        self.YScaleBox.setMinimum(-1000.0)
        self.YScaleBox.setMaximum(1000.0)
        self.YScaleBox.setProperty("value", 1.0)
        self.YScaleBox.setObjectName("YScaleBox")
        self.gridLayout.addWidget(self.YScaleBox, 1, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.offsetBox)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.XScaleBox = QtWidgets.QDoubleSpinBox(self.offsetBox)
        self.XScaleBox.setMinimum(-1000.0)
        self.XScaleBox.setMaximum(1000.0)
        self.XScaleBox.setProperty("value", 1.0)
        self.XScaleBox.setObjectName("XScaleBox")
        self.gridLayout.addWidget(self.XScaleBox, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.offsetBox)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.noiseBox = QtWidgets.QGroupBox(filterDialog)
        self.noiseBox.setCheckable(True)
        self.noiseBox.setChecked(False)
        self.noiseBox.setObjectName("noiseBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.noiseBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.noiseBox)
        self.label_9.setEnabled(False)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.horizontalLayout_6.addWidget(self.noiseBox)
        self.smoothBox = QtWidgets.QGroupBox(filterDialog)
        self.smoothBox.setCheckable(True)
        self.smoothBox.setChecked(False)
        self.smoothBox.setObjectName("smoothBox")
        self.formLayout = QtWidgets.QFormLayout(self.smoothBox)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.smoothBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.smoothComboBox = QtWidgets.QComboBox(self.smoothBox)
        self.smoothComboBox.setObjectName("smoothComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.smoothComboBox)
        self.label_2 = QtWidgets.QLabel(self.smoothBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.smoothWindowBox = QtWidgets.QSpinBox(self.smoothBox)
        self.smoothWindowBox.setMinimum(1)
        self.smoothWindowBox.setProperty("value", 5)
        self.smoothWindowBox.setObjectName("smoothWindowBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.smoothWindowBox)
        self.label_3 = QtWidgets.QLabel(self.smoothBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.smoothOrderBox = QtWidgets.QSpinBox(self.smoothBox)
        self.smoothOrderBox.setMinimum(1)
        self.smoothOrderBox.setObjectName("smoothOrderBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.smoothOrderBox)
        self.horizontalLayout_6.addWidget(self.smoothBox)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.buttonBox = QtWidgets.QDialogButtonBox(filterDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(filterDialog)
        self.addIonsTabWidget.setCurrentIndex(1)
        self.buttonBox.accepted.connect(filterDialog.accept)
        self.buttonBox.rejected.connect(filterDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(filterDialog)

    def retranslateUi(self, filterDialog):
        _translate = QtCore.QCoreApplication.translate
        filterDialog.setWindowTitle(_translate("filterDialog", "Filter Chromatogram"))
        self.ionBox.setTitle(_translate("filterDialog", "Ions / Wavelengths"))
        self.addDefinedIonButton.setText(_translate("filterDialog", "Add"))
        self.addIonsTabWidget.setTabText(self.addIonsTabWidget.indexOf(self.tab), _translate("filterDialog", "Defined"))
        self.addSingleIonButton.setText(_translate("filterDialog", "Add"))
        self.addIonsTabWidget.setTabText(self.addIonsTabWidget.indexOf(self.tab_2), _translate("filterDialog", "Single"))
        self.label_8.setText(_translate("filterDialog", "-"))
        self.addRangeIonButton.setText(_translate("filterDialog", "Add"))
        self.addIonsTabWidget.setTabText(self.addIonsTabWidget.indexOf(self.tab_3), _translate("filterDialog", "Range"))
        self.addUserIonButton.setText(_translate("filterDialog", "Add"))
        self.addIonsTabWidget.setTabText(self.addIonsTabWidget.indexOf(self.tab_4), _translate("filterDialog", "User"))
        self.offsetBox.setTitle(_translate("filterDialog", "Offset && Scaling"))
        self.label_5.setText(_translate("filterDialog", "Y Offset"))
        self.label_6.setText(_translate("filterDialog", "X Offset"))
        self.label_4.setText(_translate("filterDialog", "Y Scaling"))
        self.label_7.setText(_translate("filterDialog", "X Scaling"))
        self.noiseBox.setTitle(_translate("filterDialog", "Noise Removal"))
        self.label_9.setText(_translate("filterDialog", "Not Yet Implemented"))
        self.smoothBox.setTitle(_translate("filterDialog", "Smoothing"))
        self.label.setText(_translate("filterDialog", "Type"))
        self.label_2.setText(_translate("filterDialog", "Window"))
        self.label_3.setText(_translate("filterDialog", "Order"))

