# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './aston/qtgui/ui/ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(694, 537)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plotArea = QtWidgets.QVBoxLayout()
        self.plotArea.setObjectName("plotArea")
        self.verticalLayout.addLayout(self.plotArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 694, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuExport = QtWidgets.QMenu(self.menuFile)
        self.menuExport.setObjectName("menuExport")
        self.menuLoad = QtWidgets.QMenu(self.menuFile)
        self.menuLoad.setObjectName("menuLoad")
        self.menuChromatogram = QtWidgets.QMenu(self.menubar)
        self.menuChromatogram.setObjectName("menuChromatogram")
        self.menuIntegrand = QtWidgets.QMenu(self.menuChromatogram)
        self.menuIntegrand.setObjectName("menuIntegrand")
        self.menuSpectrum = QtWidgets.QMenu(self.menubar)
        self.menuSpectrum.setObjectName("menuSpectrum")
        self.menuCurrent = QtWidgets.QMenu(self.menuSpectrum)
        self.menuCurrent.setObjectName("menuCurrent")
        self.menuPrevious = QtWidgets.QMenu(self.menuSpectrum)
        self.menuPrevious.setObjectName("menuPrevious")
        self.menuLibrary = QtWidgets.QMenu(self.menuSpectrum)
        self.menuLibrary.setObjectName("menuLibrary")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setEnabled(False)
        self.menuHelp.setObjectName("menuHelp")
        self.menuWindows = QtWidgets.QMenu(self.menubar)
        self.menuWindows.setObjectName("menuWindows")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuPeaks = QtWidgets.QMenu(self.menuSettings)
        self.menuPeaks.setEnabled(False)
        self.menuPeaks.setObjectName("menuPeaks")
        self.menuExtras = QtWidgets.QMenu(self.menuSettings)
        self.menuExtras.setEnabled(True)
        self.menuExtras.setObjectName("menuExtras")
        self.menuAxes = QtWidgets.QMenu(self.menuSettings)
        self.menuAxes.setObjectName("menuAxes")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.filesDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.filesDockWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.filesDockWidget.setFloating(False)
        self.filesDockWidget.setObjectName("filesDockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.fileTreeView = QtWidgets.QTreeView(self.dockWidgetContents)
        self.fileTreeView.setObjectName("fileTreeView")
        self.verticalLayout_4.addWidget(self.fileTreeView)
        self.filesDockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.filesDockWidget)
        self.settingsDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.settingsDockWidget.setObjectName("settingsDockWidget")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.dockWidgetContents_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_settings = QtWidgets.QVBoxLayout()
        self.verticalLayout_settings.setObjectName("verticalLayout_settings")
        self.horizontalLayout_4.addLayout(self.verticalLayout_settings)
        self.settingsDockWidget.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.settingsDockWidget)
        self.spectraDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.spectraDockWidget.setObjectName("spectraDockWidget")
        self.dockWidgetContents_5 = QtWidgets.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.dockWidgetContents_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.specArea = QtWidgets.QVBoxLayout()
        self.specArea.setObjectName("specArea")
        self.horizontalLayout_3.addLayout(self.specArea)
        self.spectraDockWidget.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.spectraDockWidget)
        self.methodDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.methodDockWidget.setEnabled(True)
        self.methodDockWidget.setObjectName("methodDockWidget")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.methodTreeView = QtWidgets.QTreeView(self.dockWidgetContents_2)
        self.methodTreeView.setObjectName("methodTreeView")
        self.verticalLayout_2.addWidget(self.methodTreeView)
        self.methodDockWidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.methodDockWidget)
        self.compoundDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.compoundDockWidget.setObjectName("compoundDockWidget")
        self.dockWidgetContents_6 = QtWidgets.QWidget()
        self.dockWidgetContents_6.setObjectName("dockWidgetContents_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.compoundTreeView = QtWidgets.QTreeView(self.dockWidgetContents_6)
        self.compoundTreeView.setObjectName("compoundTreeView")
        self.verticalLayout_3.addWidget(self.compoundTreeView)
        self.compoundDockWidget.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.compoundDockWidget)
        self.paletteDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.paletteDockWidget.setFloating(False)
        self.paletteDockWidget.setObjectName("paletteDockWidget")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.paletteTreeView = QtWidgets.QTreeView(self.dockWidgetContents_4)
        self.paletteTreeView.setObjectName("paletteTreeView")
        self.verticalLayout_5.addWidget(self.paletteTreeView)
        self.paletteDockWidget.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.paletteDockWidget)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExportChromatogram = QtWidgets.QAction(MainWindow)
        self.actionExportChromatogram.setObjectName("actionExportChromatogram")
        self.actionChromatogram_as_CSV = QtWidgets.QAction(MainWindow)
        self.actionChromatogram_as_CSV.setEnabled(False)
        self.actionChromatogram_as_CSV.setObjectName("actionChromatogram_as_CSV")
        self.actionExportSpectra = QtWidgets.QAction(MainWindow)
        self.actionExportSpectra.setObjectName("actionExportSpectra")
        self.actionSpectra_as_CSV = QtWidgets.QAction(MainWindow)
        self.actionSpectra_as_CSV.setEnabled(False)
        self.actionSpectra_as_CSV.setObjectName("actionSpectra_as_CSV")
        self.actionExportSelectedItems = QtWidgets.QAction(MainWindow)
        self.actionExportSelectedItems.setEnabled(True)
        self.actionExportSelectedItems.setObjectName("actionExportSelectedItems")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSearch_Database = QtWidgets.QAction(MainWindow)
        self.actionSearch_Database.setEnabled(False)
        self.actionSearch_Database.setObjectName("actionSearch_Database")
        self.actionSave_to_Database = QtWidgets.QAction(MainWindow)
        self.actionSave_to_Database.setEnabled(False)
        self.actionSave_to_Database.setObjectName("actionSave_to_Database")
        self.actionSequence = QtWidgets.QAction(MainWindow)
        self.actionSequence.setEnabled(False)
        self.actionSequence.setObjectName("actionSequence")
        self.actionStructure = QtWidgets.QAction(MainWindow)
        self.actionStructure.setEnabled(False)
        self.actionStructure.setObjectName("actionStructure")
        self.actionCalculate_Info = QtWidgets.QAction(MainWindow)
        self.actionCalculate_Info.setObjectName("actionCalculate_Info")
        self.actionAutoAlignChromatogram = QtWidgets.QAction(MainWindow)
        self.actionAutoAlignChromatogram.setEnabled(False)
        self.actionAutoAlignChromatogram.setObjectName("actionAutoAlignChromatogram")
        self.actionSubtractAddChromatogram = QtWidgets.QAction(MainWindow)
        self.actionSubtractAddChromatogram.setEnabled(False)
        self.actionSubtractAddChromatogram.setObjectName("actionSubtractAddChromatogram")
        self.actionRevert = QtWidgets.QAction(MainWindow)
        self.actionRevert.setEnabled(True)
        self.actionRevert.setObjectName("actionRevert")
        self.actionEditFilters = QtWidgets.QAction(MainWindow)
        self.actionEditFilters.setObjectName("actionEditFilters")
        self.actionSmoothChromatogram = QtWidgets.QAction(MainWindow)
        self.actionSmoothChromatogram.setObjectName("actionSmoothChromatogram")
        self.actionAlign_Chromatogram = QtWidgets.QAction(MainWindow)
        self.actionAlign_Chromatogram.setObjectName("actionAlign_Chromatogram")
        self.actionCalculate_Isotopic = QtWidgets.QAction(MainWindow)
        self.actionCalculate_Isotopic.setEnabled(False)
        self.actionCalculate_Isotopic.setObjectName("actionCalculate_Isotopic")
        self.actionExport_Peak_List = QtWidgets.QAction(MainWindow)
        self.actionExport_Peak_List.setEnabled(False)
        self.actionExport_Peak_List.setObjectName("actionExport_Peak_List")
        self.actionIdentify = QtWidgets.QAction(MainWindow)
        self.actionIdentify.setEnabled(False)
        self.actionIdentify.setObjectName("actionIdentify")
        self.actionFiles = QtWidgets.QAction(MainWindow)
        self.actionFiles.setCheckable(True)
        self.actionFiles.setChecked(True)
        self.actionFiles.setObjectName("actionFiles")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setCheckable(True)
        self.actionSettings.setChecked(False)
        self.actionSettings.setObjectName("actionSettings")
        self.actionPeaks = QtWidgets.QAction(MainWindow)
        self.actionPeaks.setCheckable(True)
        self.actionPeaks.setChecked(True)
        self.actionPeaks.setObjectName("actionPeaks")
        self.actionSpectra = QtWidgets.QAction(MainWindow)
        self.actionSpectra.setCheckable(True)
        self.actionSpectra.setChecked(True)
        self.actionSpectra.setObjectName("actionSpectra")
        self.actionMethods = QtWidgets.QAction(MainWindow)
        self.actionMethods.setCheckable(True)
        self.actionMethods.setEnabled(True)
        self.actionMethods.setObjectName("actionMethods")
        self.actionCompounds = QtWidgets.QAction(MainWindow)
        self.actionCompounds.setCheckable(True)
        self.actionCompounds.setEnabled(True)
        self.actionCompounds.setObjectName("actionCompounds")
        self.actionAll_Items_as_CSV = QtWidgets.QAction(MainWindow)
        self.actionAll_Items_as_CSV.setObjectName("actionAll_Items_as_CSV")
        self.actionLegend = QtWidgets.QAction(MainWindow)
        self.actionLegend.setCheckable(True)
        self.actionLegend.setObjectName("actionLegend")
        self.actionIntegrateStatSlope = QtWidgets.QAction(MainWindow)
        self.actionIntegrateStatSlope.setCheckable(True)
        self.actionIntegrateStatSlope.setObjectName("actionIntegrateStatSlope")
        self.actionIntegrateWavelet = QtWidgets.QAction(MainWindow)
        self.actionIntegrateWavelet.setCheckable(True)
        self.actionIntegrateWavelet.setChecked(False)
        self.actionIntegrateWavelet.setObjectName("actionIntegrateWavelet")
        self.actionPeaksHide = QtWidgets.QAction(MainWindow)
        self.actionPeaksHide.setCheckable(True)
        self.actionPeaksHide.setObjectName("actionPeaksHide")
        self.actionPeaksShow = QtWidgets.QAction(MainWindow)
        self.actionPeaksShow.setCheckable(True)
        self.actionPeaksShow.setObjectName("actionPeaksShow")
        self.actionPeaksShowLabels = QtWidgets.QAction(MainWindow)
        self.actionPeaksShowLabels.setEnabled(False)
        self.actionPeaksShowLabels.setObjectName("actionPeaksShowLabels")
        self.actionGraphFxnCollection = QtWidgets.QAction(MainWindow)
        self.actionGraphFxnCollection.setCheckable(True)
        self.actionGraphFxnCollection.setObjectName("actionGraphFxnCollection")
        self.actionGraphMSMS = QtWidgets.QAction(MainWindow)
        self.actionGraphMSMS.setCheckable(True)
        self.actionGraphMSMS.setEnabled(False)
        self.actionGraphMSMS.setObjectName("actionGraphMSMS")
        self.actionIntegrateSimple = QtWidgets.QAction(MainWindow)
        self.actionIntegrateSimple.setCheckable(True)
        self.actionIntegrateSimple.setChecked(True)
        self.actionIntegrateSimple.setEnabled(True)
        self.actionIntegrateSimple.setObjectName("actionIntegrateSimple")
        self.actionGraphIRMS = QtWidgets.QAction(MainWindow)
        self.actionGraphIRMS.setCheckable(True)
        self.actionGraphIRMS.setObjectName("actionGraphIRMS")
        self.actionFIA = QtWidgets.QAction(MainWindow)
        self.actionFIA.setCheckable(True)
        self.actionFIA.setObjectName("actionFIA")
        self.actionCopy_Settings_from_Other_DB = QtWidgets.QAction(MainWindow)
        self.actionCopy_Settings_from_Other_DB.setObjectName("actionCopy_Settings_from_Other_DB")
        self.actionIntegrandActiveTrace = QtWidgets.QAction(MainWindow)
        self.actionIntegrandActiveTrace.setCheckable(True)
        self.actionIntegrandActiveTrace.setChecked(True)
        self.actionIntegrandActiveTrace.setObjectName("actionIntegrandActiveTrace")
        self.actionTop_File_Vis_Traces = QtWidgets.QAction(MainWindow)
        self.actionTop_File_Vis_Traces.setCheckable(True)
        self.actionTop_File_Vis_Traces.setObjectName("actionTop_File_Vis_Traces")
        self.actionIntegrandIndependent = QtWidgets.QAction(MainWindow)
        self.actionIntegrandIndependent.setCheckable(True)
        self.actionIntegrandIndependent.setObjectName("actionIntegrandIndependent")
        self.actionIntegrandAsFirst = QtWidgets.QAction(MainWindow)
        self.actionIntegrandAsFirst.setCheckable(True)
        self.actionIntegrandAsFirst.setObjectName("actionIntegrandAsFirst")
        self.actionSimple = QtWidgets.QAction(MainWindow)
        self.actionSimple.setCheckable(True)
        self.actionSimple.setChecked(True)
        self.actionSimple.setObjectName("actionSimple")
        self.actionWavelet = QtWidgets.QAction(MainWindow)
        self.actionWavelet.setCheckable(True)
        self.actionWavelet.setObjectName("actionWavelet")
        self.actionStatistical_Slope = QtWidgets.QAction(MainWindow)
        self.actionStatistical_Slope.setCheckable(True)
        self.actionStatistical_Slope.setObjectName("actionStatistical_Slope")
        self.actionEvent = QtWidgets.QAction(MainWindow)
        self.actionEvent.setCheckable(True)
        self.actionEvent.setObjectName("actionEvent")
        self.actionGraphFIA = QtWidgets.QAction(MainWindow)
        self.actionGraphFIA.setCheckable(True)
        self.actionGraphFIA.setObjectName("actionGraphFIA")
        self.actionIntegrate = QtWidgets.QAction(MainWindow)
        self.actionIntegrate.setObjectName("actionIntegrate")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setText("")
        self.action.setObjectName("action")
        self.actionColor_Scheme = QtWidgets.QAction(MainWindow)
        self.actionColor_Scheme.setObjectName("actionColor_Scheme")
        self.actionPeak_Finder = QtWidgets.QAction(MainWindow)
        self.actionPeak_Finder.setObjectName("actionPeak_Finder")
        self.actionIntegrator = QtWidgets.QAction(MainWindow)
        self.actionIntegrator.setObjectName("actionIntegrator")
        self.actionGraph_Peaks_Found = QtWidgets.QAction(MainWindow)
        self.actionGraph_Peaks_Found.setCheckable(True)
        self.actionGraph_Peaks_Found.setObjectName("actionGraph_Peaks_Found")
        self.actionGraph_Style = QtWidgets.QAction(MainWindow)
        self.actionGraph_Style.setObjectName("actionGraph_Style")
        self.actionSpecMainDisp = QtWidgets.QAction(MainWindow)
        self.actionSpecMainDisp.setCheckable(True)
        self.actionSpecMainDisp.setChecked(True)
        self.actionSpecMainDisp.setObjectName("actionSpecMainDisp")
        self.actionSpecMainLabel = QtWidgets.QAction(MainWindow)
        self.actionSpecMainLabel.setCheckable(True)
        self.actionSpecMainLabel.setChecked(True)
        self.actionSpecMainLabel.setObjectName("actionSpecMainLabel")
        self.actionSpecPrevDisp = QtWidgets.QAction(MainWindow)
        self.actionSpecPrevDisp.setCheckable(True)
        self.actionSpecPrevDisp.setObjectName("actionSpecPrevDisp")
        self.actionSpecPrevLabel = QtWidgets.QAction(MainWindow)
        self.actionSpecPrevLabel.setCheckable(True)
        self.actionSpecPrevLabel.setObjectName("actionSpecPrevLabel")
        self.actionSpecLibDisp = QtWidgets.QAction(MainWindow)
        self.actionSpecLibDisp.setCheckable(True)
        self.actionSpecLibDisp.setChecked(True)
        self.actionSpecLibDisp.setObjectName("actionSpecLibDisp")
        self.actionSpecLibLabel = QtWidgets.QAction(MainWindow)
        self.actionSpecLibLabel.setCheckable(True)
        self.actionSpecLibLabel.setObjectName("actionSpecLibLabel")
        self.actionSpecMainSave = QtWidgets.QAction(MainWindow)
        self.actionSpecMainSave.setObjectName("actionSpecMainSave")
        self.actionSpecPrevSave = QtWidgets.QAction(MainWindow)
        self.actionSpecPrevSave.setObjectName("actionSpecPrevSave")
        self.actionGraphLogYAxis = QtWidgets.QAction(MainWindow)
        self.actionGraphLogYAxis.setCheckable(True)
        self.actionGraphLogYAxis.setObjectName("actionGraphLogYAxis")
        self.actionGraphGrid = QtWidgets.QAction(MainWindow)
        self.actionGraphGrid.setCheckable(True)
        self.actionGraphGrid.setChecked(True)
        self.actionGraphGrid.setObjectName("actionGraphGrid")
        self.loadPeakList = QtWidgets.QAction(MainWindow)
        self.loadPeakList.setObjectName("loadPeakList")
        self.loadIsodatPeaks = QtWidgets.QAction(MainWindow)
        self.loadIsodatPeaks.setObjectName("loadIsodatPeaks")
        self.actionPalette = QtWidgets.QAction(MainWindow)
        self.actionPalette.setCheckable(True)
        self.actionPalette.setObjectName("actionPalette")
        self.menuExport.addAction(self.actionExportChromatogram)
        self.menuExport.addAction(self.actionExportSpectra)
        self.menuExport.addAction(self.actionExportSelectedItems)
        self.menuLoad.addAction(self.loadPeakList)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuLoad.menuAction())
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuIntegrand.addAction(self.actionIntegrandActiveTrace)
        self.menuIntegrand.addAction(self.actionIntegrandAsFirst)
        self.menuIntegrand.addAction(self.actionIntegrandIndependent)
        self.menuChromatogram.addAction(self.actionIntegrate)
        self.menuChromatogram.addSeparator()
        self.menuChromatogram.addAction(self.menuIntegrand.menuAction())
        self.menuChromatogram.addAction(self.actionPeak_Finder)
        self.menuChromatogram.addAction(self.actionIntegrator)
        self.menuChromatogram.addSeparator()
        self.menuChromatogram.addAction(self.actionAutoAlignChromatogram)
        self.menuChromatogram.addAction(self.actionEditFilters)
        self.menuChromatogram.addAction(self.actionRevert)
        self.menuCurrent.addAction(self.actionSpecMainDisp)
        self.menuCurrent.addAction(self.actionSpecMainLabel)
        self.menuCurrent.addAction(self.actionSpecMainSave)
        self.menuPrevious.addAction(self.actionSpecPrevDisp)
        self.menuPrevious.addAction(self.actionSpecPrevLabel)
        self.menuPrevious.addAction(self.actionSpecPrevSave)
        self.menuLibrary.addAction(self.actionSpecLibDisp)
        self.menuLibrary.addAction(self.actionSpecLibLabel)
        self.menuSpectrum.addAction(self.menuCurrent.menuAction())
        self.menuSpectrum.addAction(self.menuPrevious.menuAction())
        self.menuSpectrum.addAction(self.menuLibrary.menuAction())
        self.menuSpectrum.addSeparator()
        self.menuSpectrum.addAction(self.actionSearch_Database)
        self.menuSpectrum.addAction(self.actionSequence)
        self.menuSpectrum.addAction(self.actionStructure)
        self.menuWindows.addAction(self.actionFiles)
        self.menuWindows.addAction(self.actionPalette)
        self.menuWindows.addAction(self.actionSpectra)
        self.menuWindows.addAction(self.actionMethods)
        self.menuWindows.addAction(self.actionCompounds)
        self.menuWindows.addAction(self.actionSettings)
        self.menuPeaks.addAction(self.actionPeaksHide)
        self.menuPeaks.addAction(self.actionPeaksShow)
        self.menuPeaks.addAction(self.actionPeaksShowLabels)
        self.menuExtras.addAction(self.actionGraph_Peaks_Found)
        self.menuExtras.addAction(self.actionGraphFxnCollection)
        self.menuExtras.addAction(self.actionGraphFIA)
        self.menuExtras.addAction(self.actionGraphIRMS)
        self.menuExtras.addAction(self.actionGraphMSMS)
        self.menuAxes.addAction(self.actionGraphLogYAxis)
        self.menuAxes.addAction(self.actionGraphGrid)
        self.menuSettings.addAction(self.actionGraph_Style)
        self.menuSettings.addAction(self.actionLegend)
        self.menuSettings.addAction(self.actionColor_Scheme)
        self.menuSettings.addAction(self.menuAxes.menuAction())
        self.menuSettings.addAction(self.menuPeaks.menuAction())
        self.menuSettings.addAction(self.menuExtras.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuChromatogram.menuAction())
        self.menubar.addAction(self.menuSpectrum.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuWindows.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Aston"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.menuLoad.setTitle(_translate("MainWindow", "Load"))
        self.menuChromatogram.setTitle(_translate("MainWindow", "Chromatogram"))
        self.menuIntegrand.setTitle(_translate("MainWindow", "Integrand"))
        self.menuSpectrum.setTitle(_translate("MainWindow", "Spectrum"))
        self.menuCurrent.setTitle(_translate("MainWindow", "Current"))
        self.menuPrevious.setTitle(_translate("MainWindow", "Previous"))
        self.menuLibrary.setTitle(_translate("MainWindow", "Library"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuWindows.setTitle(_translate("MainWindow", "Windows"))
        self.menuSettings.setTitle(_translate("MainWindow", "Graph"))
        self.menuPeaks.setTitle(_translate("MainWindow", "Peaks"))
        self.menuExtras.setTitle(_translate("MainWindow", "Extras"))
        self.menuAxes.setTitle(_translate("MainWindow", "Axes"))
        self.filesDockWidget.setWindowTitle(_translate("MainWindow", "Files"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Seach by Name"))
        self.settingsDockWidget.setWindowTitle(_translate("MainWindow", "Settings"))
        self.spectraDockWidget.setWindowTitle(_translate("MainWindow", "Spectra"))
        self.methodDockWidget.setWindowTitle(_translate("MainWindow", "Methods"))
        self.compoundDockWidget.setWindowTitle(_translate("MainWindow", "Compounds"))
        self.paletteDockWidget.setWindowTitle(_translate("MainWindow", "Palette"))
        self.actionOpen.setText(_translate("MainWindow", "Open Folder"))
        self.actionExportChromatogram.setText(_translate("MainWindow", "Visible Chromatogram"))
        self.actionChromatogram_as_CSV.setText(_translate("MainWindow", "Chromatogram as CSV"))
        self.actionExportSpectra.setText(_translate("MainWindow", "Visible Spectra"))
        self.actionSpectra_as_CSV.setText(_translate("MainWindow", "Spectra as CSV"))
        self.actionExportSelectedItems.setText(_translate("MainWindow", "Selected Items"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionSearch_Database.setText(_translate("MainWindow", "Search Database"))
        self.actionSave_to_Database.setText(_translate("MainWindow", "Save to Database"))
        self.actionSequence.setText(_translate("MainWindow", "Sequence"))
        self.actionStructure.setText(_translate("MainWindow", "Structure"))
        self.actionCalculate_Info.setText(_translate("MainWindow", "Calculate Info"))
        self.actionAutoAlignChromatogram.setText(_translate("MainWindow", "Auto-Align Chromatogram"))
        self.actionSubtractAddChromatogram.setText(_translate("MainWindow", "Subtract/Add Chromatogram"))
        self.actionRevert.setText(_translate("MainWindow", "Revert to Original"))
        self.actionEditFilters.setText(_translate("MainWindow", "Edit Filters..."))
        self.actionSmoothChromatogram.setText(_translate("MainWindow", "Smooth Chromatogram"))
        self.actionAlign_Chromatogram.setText(_translate("MainWindow", "Adjust Chromatogram"))
        self.actionCalculate_Isotopic.setText(_translate("MainWindow", "Calculate Isotopic"))
        self.actionExport_Peak_List.setText(_translate("MainWindow", "Export Peak List"))
        self.actionIdentify.setText(_translate("MainWindow", "Quick Identify"))
        self.actionFiles.setText(_translate("MainWindow", "Files"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionPeaks.setText(_translate("MainWindow", "Peaks"))
        self.actionSpectra.setText(_translate("MainWindow", "Spectra"))
        self.actionMethods.setText(_translate("MainWindow", "Methods"))
        self.actionCompounds.setText(_translate("MainWindow", "Compounds"))
        self.actionAll_Items_as_CSV.setText(_translate("MainWindow", "All Items as CSV"))
        self.actionLegend.setText(_translate("MainWindow", "Legend"))
        self.actionIntegrateStatSlope.setText(_translate("MainWindow", "Drop"))
        self.actionIntegrateWavelet.setText(_translate("MainWindow", "LeastSquares"))
        self.actionPeaksHide.setText(_translate("MainWindow", "Hide"))
        self.actionPeaksShow.setText(_translate("MainWindow", "Show"))
        self.actionPeaksShowLabels.setText(_translate("MainWindow", "Show with Labels"))
        self.actionGraphFxnCollection.setText(_translate("MainWindow", "Fxn Collection"))
        self.actionGraphMSMS.setText(_translate("MainWindow", "MS-MS"))
        self.actionIntegrateSimple.setText(_translate("MainWindow", "Simple"))
        self.actionGraphIRMS.setText(_translate("MainWindow", "Gas Pulse (IRMS)"))
        self.actionFIA.setText(_translate("MainWindow", "FIA"))
        self.actionCopy_Settings_from_Other_DB.setText(_translate("MainWindow", "Load Settings from DB"))
        self.actionIntegrandActiveTrace.setText(_translate("MainWindow", "Active Trace"))
        self.actionTop_File_Vis_Traces.setText(_translate("MainWindow", "Top File - Vis. Traces"))
        self.actionIntegrandIndependent.setText(_translate("MainWindow", "Active Run - All Independent"))
        self.actionIntegrandAsFirst.setText(_translate("MainWindow", "Active Run - All as First"))
        self.actionSimple.setText(_translate("MainWindow", "Simple"))
        self.actionWavelet.setText(_translate("MainWindow", "Wavelet"))
        self.actionStatistical_Slope.setText(_translate("MainWindow", "StatSlope"))
        self.actionEvent.setText(_translate("MainWindow", "Event"))
        self.actionGraphFIA.setText(_translate("MainWindow", "Flow Injection"))
        self.actionIntegrate.setText(_translate("MainWindow", "Integrate"))
        self.actionColor_Scheme.setText(_translate("MainWindow", "Color Scheme"))
        self.actionPeak_Finder.setText(_translate("MainWindow", "Peak Finder"))
        self.actionIntegrator.setText(_translate("MainWindow", "Integrator"))
        self.actionGraph_Peaks_Found.setText(_translate("MainWindow", "Peaks Found"))
        self.actionGraph_Style.setText(_translate("MainWindow", "Graph Style"))
        self.actionSpecMainDisp.setText(_translate("MainWindow", "Display"))
        self.actionSpecMainLabel.setText(_translate("MainWindow", "Label"))
        self.actionSpecPrevDisp.setText(_translate("MainWindow", "Display"))
        self.actionSpecPrevLabel.setText(_translate("MainWindow", "Label"))
        self.actionSpecLibDisp.setText(_translate("MainWindow", "Display"))
        self.actionSpecLibLabel.setText(_translate("MainWindow", "Label"))
        self.actionSpecMainSave.setText(_translate("MainWindow", "Save"))
        self.actionSpecPrevSave.setText(_translate("MainWindow", "Save"))
        self.actionGraphLogYAxis.setText(_translate("MainWindow", "Log Y Axis"))
        self.actionGraphGrid.setText(_translate("MainWindow", "Grid"))
        self.loadPeakList.setText(_translate("MainWindow", "Peak List"))
        self.loadIsodatPeaks.setText(_translate("MainWindow", "Isodat Results"))
        self.actionPalette.setText(_translate("MainWindow", "Palette"))

