# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './aston/qtgui/ui/ui_settings.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 372)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toolBox = QtWidgets.QToolBox(self.tab)
        self.toolBox.setEnabled(True)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 499, 170))
        self.page.setObjectName("page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.doubleSimpleStartSlope = QtWidgets.QDoubleSpinBox(self.page)
        self.doubleSimpleStartSlope.setMinimum(-100000000.0)
        self.doubleSimpleStartSlope.setMaximum(100000000.0)
        self.doubleSimpleStartSlope.setSingleStep(100.0)
        self.doubleSimpleStartSlope.setProperty("value", 500.0)
        self.doubleSimpleStartSlope.setObjectName("doubleSimpleStartSlope")
        self.gridLayout_4.addWidget(self.doubleSimpleStartSlope, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.doubleSimpleMaxPeakWidth = QtWidgets.QDoubleSpinBox(self.page)
        self.doubleSimpleMaxPeakWidth.setMaximum(600.0)
        self.doubleSimpleMaxPeakWidth.setProperty("value", 1.5)
        self.doubleSimpleMaxPeakWidth.setObjectName("doubleSimpleMaxPeakWidth")
        self.gridLayout_4.addWidget(self.doubleSimpleMaxPeakWidth, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 2, 2, 1, 1)
        self.doubleSimpleMinPeakHgt = QtWidgets.QDoubleSpinBox(self.page)
        self.doubleSimpleMinPeakHgt.setMaximum(1000000000.0)
        self.doubleSimpleMinPeakHgt.setSingleStep(100.0)
        self.doubleSimpleMinPeakHgt.setProperty("value", 50.0)
        self.doubleSimpleMinPeakHgt.setObjectName("doubleSimpleMinPeakHgt")
        self.gridLayout_4.addWidget(self.doubleSimpleMinPeakHgt, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 3, 0, 1, 1)
        self.doubleSimpleEndSlope = QtWidgets.QDoubleSpinBox(self.page)
        self.doubleSimpleEndSlope.setMinimum(-100000000.0)
        self.doubleSimpleEndSlope.setMaximum(100000000.0)
        self.doubleSimpleEndSlope.setSingleStep(100.0)
        self.doubleSimpleEndSlope.setProperty("value", 200.0)
        self.doubleSimpleEndSlope.setObjectName("doubleSimpleEndSlope")
        self.gridLayout_4.addWidget(self.doubleSimpleEndSlope, 3, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.page)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 2, 0, 1, 1)
        self.doubleSimpleInitSlope = QtWidgets.QDoubleSpinBox(self.page)
        self.doubleSimpleInitSlope.setMinimum(-100000000.0)
        self.doubleSimpleInitSlope.setMaximum(100000000.0)
        self.doubleSimpleInitSlope.setProperty("value", 500.0)
        self.doubleSimpleInitSlope.setObjectName("doubleSimpleInitSlope")
        self.gridLayout_4.addWidget(self.doubleSimpleInitSlope, 2, 1, 1, 1)
        self.toolBox.addItem(self.page, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 416, 187))
        self.page_3.setObjectName("page_3")
        self.gridLayout = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_17 = QtWidgets.QLabel(self.page_3)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.page_3)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 0, 1, 1)
        self.doubleWaveletAssSig = QtWidgets.QDoubleSpinBox(self.page_3)
        self.doubleWaveletAssSig.setProperty("value", 4.0)
        self.doubleWaveletAssSig.setObjectName("doubleWaveletAssSig")
        self.gridLayout.addWidget(self.doubleWaveletAssSig, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.page_3)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 0, 1, 1)
        self.doubleWaveletMinSNR = QtWidgets.QDoubleSpinBox(self.page_3)
        self.doubleWaveletMinSNR.setProperty("value", 1.0)
        self.doubleWaveletMinSNR.setObjectName("doubleWaveletMinSNR")
        self.gridLayout.addWidget(self.doubleWaveletMinSNR, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.page_3)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 1, 2, 1, 1)
        self.doubleWaveletMinLength = QtWidgets.QDoubleSpinBox(self.page_3)
        self.doubleWaveletMinLength.setProperty("value", 8.0)
        self.doubleWaveletMinLength.setObjectName("doubleWaveletMinLength")
        self.gridLayout.addWidget(self.doubleWaveletMinLength, 0, 3, 1, 1)
        self.doubleWaveletMaxDist = QtWidgets.QDoubleSpinBox(self.page_3)
        self.doubleWaveletMaxDist.setProperty("value", 4.0)
        self.doubleWaveletMaxDist.setObjectName("doubleWaveletMaxDist")
        self.gridLayout.addWidget(self.doubleWaveletMaxDist, 1, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.page_3)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 2, 0, 1, 1)
        self.doubleWaveletGapThresh = QtWidgets.QDoubleSpinBox(self.page_3)
        self.doubleWaveletGapThresh.setProperty("value", 2.0)
        self.doubleWaveletGapThresh.setObjectName("doubleWaveletGapThresh")
        self.gridLayout.addWidget(self.doubleWaveletGapThresh, 2, 1, 1, 1)
        self.toolBox.addItem(self.page_3, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 416, 187))
        self.page_2.setObjectName("page_2")
        self.formLayout = QtWidgets.QFormLayout(self.page_2)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.checkEventAdjust = QtWidgets.QCheckBox(self.page_2)
        self.checkEventAdjust.setText("")
        self.checkEventAdjust.setObjectName("checkEventAdjust")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.checkEventAdjust)
        self.toolBox.addItem(self.page_2, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 416, 92))
        self.page_4.setObjectName("page_4")
        self.formLayout_6 = QtWidgets.QFormLayout(self.page_4)
        self.formLayout_6.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_14 = QtWidgets.QLabel(self.page_4)
        self.label_14.setObjectName("label_14")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.comboLeastSqPeakModel = QtWidgets.QComboBox(self.page_4)
        self.comboLeastSqPeakModel.setObjectName("comboLeastSqPeakModel")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboLeastSqPeakModel)
        self.toolBox.addItem(self.page_4, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 416, 187))
        self.page_5.setObjectName("page_5")
        self.formLayout_3 = QtWidgets.QFormLayout(self.page_5)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_15 = QtWidgets.QLabel(self.page_5)
        self.label_15.setEnabled(True)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.doublePeriodicOffset = QtWidgets.QDoubleSpinBox(self.page_5)
        self.doublePeriodicOffset.setEnabled(True)
        self.doublePeriodicOffset.setObjectName("doublePeriodicOffset")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doublePeriodicOffset)
        self.label_16 = QtWidgets.QLabel(self.page_5)
        self.label_16.setEnabled(True)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.doublePeriodicPeriod = QtWidgets.QDoubleSpinBox(self.page_5)
        self.doublePeriodicPeriod.setEnabled(True)
        self.doublePeriodicPeriod.setProperty("value", 1.0)
        self.doublePeriodicPeriod.setObjectName("doublePeriodicPeriod")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doublePeriodicPeriod)
        self.toolBox.addItem(self.page_5, "")
        self.verticalLayout_2.addWidget(self.toolBox)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.tab_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboIsotopeKs = QtWidgets.QComboBox(self.tab_2)
        self.comboIsotopeKs.setObjectName("comboIsotopeKs")
        self.comboIsotopeKs.addItem("")
        self.comboIsotopeKs.addItem("")
        self.comboIsotopeKs.addItem("")
        self.comboIsotopeKs.addItem("")
        self.comboIsotopeKs.addItem("")
        self.comboIsotopeKs.addItem("")
        self.comboIsotopeKs.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboIsotopeKs)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboIsotopeMethod = QtWidgets.QComboBox(self.tab_2)
        self.comboIsotopeMethod.setObjectName("comboIsotopeMethod")
        self.comboIsotopeMethod.addItem("")
        self.comboIsotopeMethod.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboIsotopeMethod)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayout_5 = QtWidgets.QFormLayout(self.tab_3)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_21 = QtWidgets.QLabel(self.tab_3)
        self.label_21.setEnabled(False)
        self.label_21.setObjectName("label_21")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.comboIdentMethod = QtWidgets.QComboBox(self.tab_3)
        self.comboIdentMethod.setObjectName("comboIdentMethod")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboIdentMethod)
        self.label_22 = QtWidgets.QLabel(self.tab_3)
        self.label_22.setEnabled(False)
        self.label_22.setObjectName("label_22")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.doubleIdentCutoff = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleIdentCutoff.setEnabled(False)
        self.doubleIdentCutoff.setObjectName("doubleIdentCutoff")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleIdentCutoff)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.toolBox_2 = QtWidgets.QToolBox(self.tab_4)
        self.toolBox_2.setObjectName("toolBox_2")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 416, 265))
        self.page_6.setObjectName("page_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_8 = QtWidgets.QLabel(self.page_6)
        self.label_8.setEnabled(True)
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineCompoundDB = QtWidgets.QLineEdit(self.page_6)
        self.lineCompoundDB.setEnabled(True)
        self.lineCompoundDB.setReadOnly(True)
        self.lineCompoundDB.setObjectName("lineCompoundDB")
        self.horizontalLayout_2.addWidget(self.lineCompoundDB)
        self.btnOpenCompoundDB = QtWidgets.QPushButton(self.page_6)
        self.btnOpenCompoundDB.setObjectName("btnOpenCompoundDB")
        self.horizontalLayout_2.addWidget(self.btnOpenCompoundDB)
        self.formLayout_4.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_9 = QtWidgets.QLabel(self.page_6)
        self.label_9.setEnabled(True)
        self.label_9.setObjectName("label_9")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineMethodDB = QtWidgets.QLineEdit(self.page_6)
        self.lineMethodDB.setEnabled(True)
        self.lineMethodDB.setReadOnly(True)
        self.lineMethodDB.setObjectName("lineMethodDB")
        self.horizontalLayout.addWidget(self.lineMethodDB)
        self.btnOpenMethodDB = QtWidgets.QPushButton(self.page_6)
        self.btnOpenMethodDB.setObjectName("btnOpenMethodDB")
        self.horizontalLayout.addWidget(self.btnOpenMethodDB)
        self.formLayout_4.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_10 = QtWidgets.QLabel(self.page_6)
        self.label_10.setObjectName("label_10")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.checkDBRescan = QtWidgets.QCheckBox(self.page_6)
        self.checkDBRescan.setText("")
        self.checkDBRescan.setChecked(True)
        self.checkDBRescan.setObjectName("checkDBRescan")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkDBRescan)
        self.label_11 = QtWidgets.QLabel(self.page_6)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.checkDBRemoveDeleted = QtWidgets.QCheckBox(self.page_6)
        self.checkDBRemoveDeleted.setText("")
        self.checkDBRemoveDeleted.setObjectName("checkDBRemoveDeleted")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkDBRemoveDeleted)
        self.verticalLayout_4.addLayout(self.formLayout_4)
        self.pushButtonCopyDB = QtWidgets.QPushButton(self.page_6)
        self.pushButtonCopyDB.setObjectName("pushButtonCopyDB")
        self.verticalLayout_4.addWidget(self.pushButtonCopyDB)
        self.toolBox_2.addItem(self.page_6, "")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 159, 29))
        self.page_7.setObjectName("page_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkMultiprocessing = QtWidgets.QCheckBox(self.page_7)
        self.checkMultiprocessing.setChecked(True)
        self.checkMultiprocessing.setObjectName("checkMultiprocessing")
        self.verticalLayout_5.addWidget(self.checkMultiprocessing)
        self.toolBox_2.addItem(self.page_7, "")
        self.verticalLayout_3.addWidget(self.toolBox_2)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(4)
        self.comboIsotopeKs.setCurrentIndex(3)
        self.toolBox_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Starting Slope"))
        self.label_7.setText(_translate("Form", "Min Peak Height"))
        self.label_6.setText(_translate("Form", "Max Peak Width (min)"))
        self.label_5.setText(_translate("Form", "Ending Slope"))
        self.label_20.setText(_translate("Form", "Peak Init Slope"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Form", "Simple Peak Finder"))
        self.label_17.setText(_translate("Form", "Min Length"))
        self.label_13.setText(_translate("Form", "Assumed Sigma"))
        self.label_12.setText(_translate("Form", "Minimum Signal-Noise Ratio"))
        self.label_18.setText(_translate("Form", "Max Dist"))
        self.label_19.setText(_translate("Form", "Gap Thresh"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("Form", "Wavelet Peak Finder"))
        self.label_3.setText(_translate("Form", "Adjust Times"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("Form", "Event Peak Finder"))
        self.label_14.setText(_translate("Form", "Peak Model"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("Form", "LeastSq Integrator"))
        self.label_15.setText(_translate("Form", "Offset"))
        self.label_16.setText(_translate("Form", "Period"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("Form", "Periodic Integrator"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Peak Finders && Integrators"))
        self.label.setText(_translate("Form", "Constants"))
        self.comboIsotopeKs.setItemText(0, _translate("Form", "Craig"))
        self.comboIsotopeKs.setItemText(1, _translate("Form", "IAEA"))
        self.comboIsotopeKs.setItemText(2, _translate("Form", "Warner"))
        self.comboIsotopeKs.setItemText(3, _translate("Form", "Santrock"))
        self.comboIsotopeKs.setItemText(4, _translate("Form", "Assonov"))
        self.comboIsotopeKs.setItemText(5, _translate("Form", "Assonov2"))
        self.comboIsotopeKs.setItemText(6, _translate("Form", "Isodat"))
        self.label_2.setText(_translate("Form", "Method"))
        self.comboIsotopeMethod.setItemText(0, _translate("Form", "Santrock-Studley-Hayes"))
        self.comboIsotopeMethod.setItemText(1, _translate("Form", "Craig"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Isotopes"))
        self.label_21.setText(_translate("Form", "Spectral Match Method"))
        self.label_22.setText(_translate("Form", "Match Cutoff"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Identification"))
        self.label_8.setText(_translate("Form", "Compound DB"))
        self.btnOpenCompoundDB.setText(_translate("Form", "Open"))
        self.label_9.setText(_translate("Form", "Method DB"))
        self.btnOpenMethodDB.setText(_translate("Form", "Open"))
        self.label_10.setText(_translate("Form", "Rescan on Open"))
        self.label_11.setText(_translate("Form", "Remove Deleted Files"))
        self.pushButtonCopyDB.setText(_translate("Form", "Copy Settings from Other AstonDB"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_6), _translate("Form", "Database"))
        self.checkMultiprocessing.setText(_translate("Form", "Use Multiprocessing"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_7), _translate("Form", "Misc Options"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Aston"))

