# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aston_settings.ui'
#
# Created: Wed Mar 13 22:09:43 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(450, 372)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.toolBox = QtGui.QToolBox(self.tab)
        self.toolBox.setEnabled(True)
        self.toolBox.setFrameShadow(QtGui.QFrame.Plain)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 499, 170))
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_4 = QtGui.QGridLayout(self.page)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.doubleSimpleStartSlope = QtGui.QDoubleSpinBox(self.page)
        self.doubleSimpleStartSlope.setMinimum(-100000000.0)
        self.doubleSimpleStartSlope.setMaximum(100000000.0)
        self.doubleSimpleStartSlope.setSingleStep(100.0)
        self.doubleSimpleStartSlope.setProperty("value", 500.0)
        self.doubleSimpleStartSlope.setObjectName(_fromUtf8("doubleSimpleStartSlope"))
        self.gridLayout_4.addWidget(self.doubleSimpleStartSlope, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.page)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.doubleSimpleMaxPeakWidth = QtGui.QDoubleSpinBox(self.page)
        self.doubleSimpleMaxPeakWidth.setMaximum(600.0)
        self.doubleSimpleMaxPeakWidth.setProperty("value", 1.5)
        self.doubleSimpleMaxPeakWidth.setObjectName(_fromUtf8("doubleSimpleMaxPeakWidth"))
        self.gridLayout_4.addWidget(self.doubleSimpleMaxPeakWidth, 0, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.page)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 2, 2, 1, 1)
        self.doubleSimpleMinPeakHgt = QtGui.QDoubleSpinBox(self.page)
        self.doubleSimpleMinPeakHgt.setMaximum(1000000000.0)
        self.doubleSimpleMinPeakHgt.setSingleStep(100.0)
        self.doubleSimpleMinPeakHgt.setProperty("value", 50.0)
        self.doubleSimpleMinPeakHgt.setObjectName(_fromUtf8("doubleSimpleMinPeakHgt"))
        self.gridLayout_4.addWidget(self.doubleSimpleMinPeakHgt, 2, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.page)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.page)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 3, 0, 1, 1)
        self.doubleSimpleEndSlope = QtGui.QDoubleSpinBox(self.page)
        self.doubleSimpleEndSlope.setMinimum(-100000000.0)
        self.doubleSimpleEndSlope.setMaximum(100000000.0)
        self.doubleSimpleEndSlope.setSingleStep(100.0)
        self.doubleSimpleEndSlope.setProperty("value", 200.0)
        self.doubleSimpleEndSlope.setObjectName(_fromUtf8("doubleSimpleEndSlope"))
        self.gridLayout_4.addWidget(self.doubleSimpleEndSlope, 3, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.page)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_4.addWidget(self.label_20, 2, 0, 1, 1)
        self.doubleSimpleInitSlope = QtGui.QDoubleSpinBox(self.page)
        self.doubleSimpleInitSlope.setMinimum(-100000000.0)
        self.doubleSimpleInitSlope.setMaximum(100000000.0)
        self.doubleSimpleInitSlope.setProperty("value", 500.0)
        self.doubleSimpleInitSlope.setObjectName(_fromUtf8("doubleSimpleInitSlope"))
        self.gridLayout_4.addWidget(self.doubleSimpleInitSlope, 2, 1, 1, 1)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 416, 187))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.gridLayout = QtGui.QGridLayout(self.page_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_17 = QtGui.QLabel(self.page_3)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 0, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.page_3)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 1, 0, 1, 1)
        self.doubleWaveletAssSig = QtGui.QDoubleSpinBox(self.page_3)
        self.doubleWaveletAssSig.setProperty("value", 4.0)
        self.doubleWaveletAssSig.setObjectName(_fromUtf8("doubleWaveletAssSig"))
        self.gridLayout.addWidget(self.doubleWaveletAssSig, 1, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.page_3)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 0, 0, 1, 1)
        self.doubleWaveletMinSNR = QtGui.QDoubleSpinBox(self.page_3)
        self.doubleWaveletMinSNR.setProperty("value", 1.0)
        self.doubleWaveletMinSNR.setObjectName(_fromUtf8("doubleWaveletMinSNR"))
        self.gridLayout.addWidget(self.doubleWaveletMinSNR, 0, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.page_3)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 1, 2, 1, 1)
        self.doubleWaveletMinLength = QtGui.QDoubleSpinBox(self.page_3)
        self.doubleWaveletMinLength.setProperty("value", 8.0)
        self.doubleWaveletMinLength.setObjectName(_fromUtf8("doubleWaveletMinLength"))
        self.gridLayout.addWidget(self.doubleWaveletMinLength, 0, 3, 1, 1)
        self.doubleWaveletMaxDist = QtGui.QDoubleSpinBox(self.page_3)
        self.doubleWaveletMaxDist.setProperty("value", 4.0)
        self.doubleWaveletMaxDist.setObjectName(_fromUtf8("doubleWaveletMaxDist"))
        self.gridLayout.addWidget(self.doubleWaveletMaxDist, 1, 3, 1, 1)
        self.label_19 = QtGui.QLabel(self.page_3)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 2, 0, 1, 1)
        self.doubleWaveletGapThresh = QtGui.QDoubleSpinBox(self.page_3)
        self.doubleWaveletGapThresh.setProperty("value", 2.0)
        self.doubleWaveletGapThresh.setObjectName(_fromUtf8("doubleWaveletGapThresh"))
        self.gridLayout.addWidget(self.doubleWaveletGapThresh, 2, 1, 1, 1)
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 416, 187))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.formLayout = QtGui.QFormLayout(self.page_2)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.page_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.checkEventAdjust = QtGui.QCheckBox(self.page_2)
        self.checkEventAdjust.setText(_fromUtf8(""))
        self.checkEventAdjust.setObjectName(_fromUtf8("checkEventAdjust"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.checkEventAdjust)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 416, 92))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.formLayout_6 = QtGui.QFormLayout(self.page_4)
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_14 = QtGui.QLabel(self.page_4)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_14)
        self.comboLeastSqPeakModel = QtGui.QComboBox(self.page_4)
        self.comboLeastSqPeakModel.setObjectName(_fromUtf8("comboLeastSqPeakModel"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboLeastSqPeakModel)
        self.toolBox.addItem(self.page_4, _fromUtf8(""))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 416, 187))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.formLayout_3 = QtGui.QFormLayout(self.page_5)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_15 = QtGui.QLabel(self.page_5)
        self.label_15.setEnabled(True)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_15)
        self.doublePeriodicOffset = QtGui.QDoubleSpinBox(self.page_5)
        self.doublePeriodicOffset.setEnabled(True)
        self.doublePeriodicOffset.setObjectName(_fromUtf8("doublePeriodicOffset"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.doublePeriodicOffset)
        self.label_16 = QtGui.QLabel(self.page_5)
        self.label_16.setEnabled(True)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_16)
        self.doublePeriodicPeriod = QtGui.QDoubleSpinBox(self.page_5)
        self.doublePeriodicPeriod.setEnabled(True)
        self.doublePeriodicPeriod.setProperty("value", 1.0)
        self.doublePeriodicPeriod.setObjectName(_fromUtf8("doublePeriodicPeriod"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.doublePeriodicPeriod)
        self.toolBox.addItem(self.page_5, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.toolBox)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.tab_2)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.comboIsotopeKs = QtGui.QComboBox(self.tab_2)
        self.comboIsotopeKs.setObjectName(_fromUtf8("comboIsotopeKs"))
        self.comboIsotopeKs.addItem(_fromUtf8(""))
        self.comboIsotopeKs.addItem(_fromUtf8(""))
        self.comboIsotopeKs.addItem(_fromUtf8(""))
        self.comboIsotopeKs.addItem(_fromUtf8(""))
        self.comboIsotopeKs.addItem(_fromUtf8(""))
        self.comboIsotopeKs.addItem(_fromUtf8(""))
        self.comboIsotopeKs.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboIsotopeKs)
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.comboIsotopeMethod = QtGui.QComboBox(self.tab_2)
        self.comboIsotopeMethod.setObjectName(_fromUtf8("comboIsotopeMethod"))
        self.comboIsotopeMethod.addItem(_fromUtf8(""))
        self.comboIsotopeMethod.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboIsotopeMethod)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.formLayout_5 = QtGui.QFormLayout(self.tab_3)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_21 = QtGui.QLabel(self.tab_3)
        self.label_21.setEnabled(False)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_21)
        self.comboIdentMethod = QtGui.QComboBox(self.tab_3)
        self.comboIdentMethod.setObjectName(_fromUtf8("comboIdentMethod"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboIdentMethod)
        self.label_22 = QtGui.QLabel(self.tab_3)
        self.label_22.setEnabled(False)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_22)
        self.doubleIdentCutoff = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleIdentCutoff.setEnabled(False)
        self.doubleIdentCutoff.setObjectName(_fromUtf8("doubleIdentCutoff"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleIdentCutoff)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.toolBox_2 = QtGui.QToolBox(self.tab_4)
        self.toolBox_2.setObjectName(_fromUtf8("toolBox_2"))
        self.page_6 = QtGui.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 416, 265))
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page_6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_8 = QtGui.QLabel(self.page_6)
        self.label_8.setEnabled(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lineCompoundDB = QtGui.QLineEdit(self.page_6)
        self.lineCompoundDB.setEnabled(True)
        self.lineCompoundDB.setReadOnly(True)
        self.lineCompoundDB.setObjectName(_fromUtf8("lineCompoundDB"))
        self.horizontalLayout_2.addWidget(self.lineCompoundDB)
        self.btnOpenCompoundDB = QtGui.QPushButton(self.page_6)
        self.btnOpenCompoundDB.setObjectName(_fromUtf8("btnOpenCompoundDB"))
        self.horizontalLayout_2.addWidget(self.btnOpenCompoundDB)
        self.formLayout_4.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_9 = QtGui.QLabel(self.page_6)
        self.label_9.setEnabled(True)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineMethodDB = QtGui.QLineEdit(self.page_6)
        self.lineMethodDB.setEnabled(True)
        self.lineMethodDB.setReadOnly(True)
        self.lineMethodDB.setObjectName(_fromUtf8("lineMethodDB"))
        self.horizontalLayout.addWidget(self.lineMethodDB)
        self.btnOpenMethodDB = QtGui.QPushButton(self.page_6)
        self.btnOpenMethodDB.setObjectName(_fromUtf8("btnOpenMethodDB"))
        self.horizontalLayout.addWidget(self.btnOpenMethodDB)
        self.formLayout_4.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_10 = QtGui.QLabel(self.page_6)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_10)
        self.checkDBRescan = QtGui.QCheckBox(self.page_6)
        self.checkDBRescan.setText(_fromUtf8(""))
        self.checkDBRescan.setChecked(True)
        self.checkDBRescan.setObjectName(_fromUtf8("checkDBRescan"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.checkDBRescan)
        self.label_11 = QtGui.QLabel(self.page_6)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_11)
        self.checkDBRemoveDeleted = QtGui.QCheckBox(self.page_6)
        self.checkDBRemoveDeleted.setText(_fromUtf8(""))
        self.checkDBRemoveDeleted.setObjectName(_fromUtf8("checkDBRemoveDeleted"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.checkDBRemoveDeleted)
        self.verticalLayout_4.addLayout(self.formLayout_4)
        self.pushButtonCopyDB = QtGui.QPushButton(self.page_6)
        self.pushButtonCopyDB.setObjectName(_fromUtf8("pushButtonCopyDB"))
        self.verticalLayout_4.addWidget(self.pushButtonCopyDB)
        self.toolBox_2.addItem(self.page_6, _fromUtf8(""))
        self.page_7 = QtGui.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 159, 29))
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page_7)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.checkMultiprocessing = QtGui.QCheckBox(self.page_7)
        self.checkMultiprocessing.setChecked(True)
        self.checkMultiprocessing.setObjectName(_fromUtf8("checkMultiprocessing"))
        self.verticalLayout_5.addWidget(self.checkMultiprocessing)
        self.toolBox_2.addItem(self.page_7, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.toolBox_2)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(4)
        self.comboIsotopeKs.setCurrentIndex(3)
        self.toolBox_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label_4.setText(_translate("Form", "Starting Slope", None))
        self.label_7.setText(_translate("Form", "Min Peak Height", None))
        self.label_6.setText(_translate("Form", "Max Peak Width (min)", None))
        self.label_5.setText(_translate("Form", "Ending Slope", None))
        self.label_20.setText(_translate("Form", "Peak Init Slope", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Form", "Simple Peak Finder", None))
        self.label_17.setText(_translate("Form", "Min Length", None))
        self.label_13.setText(_translate("Form", "Assumed Sigma", None))
        self.label_12.setText(_translate("Form", "Minimum Signal-Noise Ratio", None))
        self.label_18.setText(_translate("Form", "Max Dist", None))
        self.label_19.setText(_translate("Form", "Gap Thresh", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("Form", "Wavelet Peak Finder", None))
        self.label_3.setText(_translate("Form", "Adjust Times", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("Form", "Event Peak Finder", None))
        self.label_14.setText(_translate("Form", "Peak Model", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("Form", "LeastSq Integrator", None))
        self.label_15.setText(_translate("Form", "Offset", None))
        self.label_16.setText(_translate("Form", "Period", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("Form", "Periodic Integrator", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Peak Finders && Integrators", None))
        self.label.setText(_translate("Form", "Constants", None))
        self.comboIsotopeKs.setItemText(0, _translate("Form", "Craig", None))
        self.comboIsotopeKs.setItemText(1, _translate("Form", "IAEA", None))
        self.comboIsotopeKs.setItemText(2, _translate("Form", "Warner", None))
        self.comboIsotopeKs.setItemText(3, _translate("Form", "Santrock", None))
        self.comboIsotopeKs.setItemText(4, _translate("Form", "Assonov", None))
        self.comboIsotopeKs.setItemText(5, _translate("Form", "Assonov2", None))
        self.comboIsotopeKs.setItemText(6, _translate("Form", "Isodat", None))
        self.label_2.setText(_translate("Form", "Method", None))
        self.comboIsotopeMethod.setItemText(0, _translate("Form", "Santrock-Studley-Hayes", None))
        self.comboIsotopeMethod.setItemText(1, _translate("Form", "Craig", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Isotopes", None))
        self.label_21.setText(_translate("Form", "Spectral Match Method", None))
        self.label_22.setText(_translate("Form", "Match Cutoff", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Identification", None))
        self.label_8.setText(_translate("Form", "Compound DB", None))
        self.btnOpenCompoundDB.setText(_translate("Form", "Open", None))
        self.label_9.setText(_translate("Form", "Method DB", None))
        self.btnOpenMethodDB.setText(_translate("Form", "Open", None))
        self.label_10.setText(_translate("Form", "Rescan on Open", None))
        self.label_11.setText(_translate("Form", "Remove Deleted Files", None))
        self.pushButtonCopyDB.setText(_translate("Form", "Copy Settings from Other AstonDB", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_6), _translate("Form", "Database", None))
        self.checkMultiprocessing.setText(_translate("Form", "Use Multiprocessing", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_7), _translate("Form", "Misc Options", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Aston", None))

