# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aston_settings.ui'
#
# Created: Thu Jan 31 18:38:49 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(450, 372)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.toolBox = QtGui.QToolBox(self.tab)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 447, 196))
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_4 = QtGui.QGridLayout(self.page)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_5 = QtGui.QLabel(self.page)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 1, 0, 1, 1)
        self.doubleSimpleEndSlope = QtGui.QDoubleSpinBox(self.page)
        self.doubleSimpleEndSlope.setMinimum(-10000.0)
        self.doubleSimpleEndSlope.setMaximum(10000.0)
        self.doubleSimpleEndSlope.setSingleStep(100.0)
        self.doubleSimpleEndSlope.setProperty("value", 200.0)
        self.doubleSimpleEndSlope.setObjectName(_fromUtf8("doubleSimpleEndSlope"))
        self.gridLayout_4.addWidget(self.doubleSimpleEndSlope, 1, 1, 1, 1)
        self.doubleSpinSimpleStartSlope = QtGui.QDoubleSpinBox(self.page)
        self.doubleSpinSimpleStartSlope.setMinimum(-10000.0)
        self.doubleSpinSimpleStartSlope.setMaximum(10000.0)
        self.doubleSpinSimpleStartSlope.setSingleStep(100.0)
        self.doubleSpinSimpleStartSlope.setProperty("value", 500.0)
        self.doubleSpinSimpleStartSlope.setObjectName(_fromUtf8("doubleSpinSimpleStartSlope"))
        self.gridLayout_4.addWidget(self.doubleSpinSimpleStartSlope, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.page)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.page)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 0, 2, 1, 1)
        self.doubleSpinSimpleMaxPeakWidth = QtGui.QDoubleSpinBox(self.page)
        self.doubleSpinSimpleMaxPeakWidth.setProperty("value", 1.5)
        self.doubleSpinSimpleMaxPeakWidth.setObjectName(_fromUtf8("doubleSpinSimpleMaxPeakWidth"))
        self.gridLayout_4.addWidget(self.doubleSpinSimpleMaxPeakWidth, 0, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.page)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 1, 2, 1, 1)
        self.doubleSpinSimpleMinPeakHgt = QtGui.QDoubleSpinBox(self.page)
        self.doubleSpinSimpleMinPeakHgt.setMaximum(10000000.0)
        self.doubleSpinSimpleMinPeakHgt.setSingleStep(100.0)
        self.doubleSpinSimpleMinPeakHgt.setProperty("value", 50.0)
        self.doubleSpinSimpleMinPeakHgt.setObjectName(_fromUtf8("doubleSpinSimpleMinPeakHgt"))
        self.gridLayout_4.addWidget(self.doubleSpinSimpleMinPeakHgt, 1, 3, 1, 1)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 247, 56))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.formLayout_5 = QtGui.QFormLayout(self.page_3)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_12 = QtGui.QLabel(self.page_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_12)
        self.doubleSpinWaveletMinSNR = QtGui.QDoubleSpinBox(self.page_3)
        self.doubleSpinWaveletMinSNR.setProperty("value", 1.0)
        self.doubleSpinWaveletMinSNR.setObjectName(_fromUtf8("doubleSpinWaveletMinSNR"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinWaveletMinSNR)
        self.doubleSpinWaveletAssSig = QtGui.QDoubleSpinBox(self.page_3)
        self.doubleSpinWaveletAssSig.setProperty("value", 4.0)
        self.doubleSpinWaveletAssSig.setObjectName(_fromUtf8("doubleSpinWaveletAssSig"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinWaveletAssSig)
        self.label_13 = QtGui.QLabel(self.page_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_13)
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 416, 213))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.formLayout_6 = QtGui.QFormLayout(self.page_4)
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_14 = QtGui.QLabel(self.page_4)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_14)
        self.comboLeastSqPeakModel = QtGui.QComboBox(self.page_4)
        self.comboLeastSqPeakModel.setObjectName(_fromUtf8("comboLeastSqPeakModel"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboLeastSqPeakModel)
        self.toolBox.addItem(self.page_4, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.toolBox)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.tab_2)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.comboIsotopeKs = QtGui.QComboBox(self.tab_2)
        self.comboIsotopeKs.setObjectName(_fromUtf8("comboIsotopeKs"))
        self.comboIsotopeKs.addItem(_fromUtf8(""))
        self.comboIsotopeKs.addItem(_fromUtf8(""))
        self.comboIsotopeKs.addItem(_fromUtf8(""))
        self.comboIsotopeKs.addItem(_fromUtf8(""))
        self.comboIsotopeKs.addItem(_fromUtf8(""))
        self.comboIsotopeKs.addItem(_fromUtf8(""))
        self.comboIsotopeKs.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboIsotopeKs)
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.comboIsotopeMethod = QtGui.QComboBox(self.tab_2)
        self.comboIsotopeMethod.setObjectName(_fromUtf8("comboIsotopeMethod"))
        self.comboIsotopeMethod.addItem(_fromUtf8(""))
        self.comboIsotopeMethod.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboIsotopeMethod)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_8 = QtGui.QLabel(self.tab_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.lineCompoundDB = QtGui.QLineEdit(self.tab_4)
        self.lineCompoundDB.setObjectName(_fromUtf8("lineCompoundDB"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineCompoundDB)
        self.label_9 = QtGui.QLabel(self.tab_4)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.lineMethodDB = QtGui.QLineEdit(self.tab_4)
        self.lineMethodDB.setObjectName(_fromUtf8("lineMethodDB"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineMethodDB)
        self.checkDBRescan = QtGui.QCheckBox(self.tab_4)
        self.checkDBRescan.setText(_fromUtf8(""))
        self.checkDBRescan.setChecked(True)
        self.checkDBRescan.setObjectName(_fromUtf8("checkDBRescan"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.checkDBRescan)
        self.label_10 = QtGui.QLabel(self.tab_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtGui.QLabel(self.tab_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_11)
        self.checkDBRemoveDeleted = QtGui.QCheckBox(self.tab_4)
        self.checkDBRemoveDeleted.setText(_fromUtf8(""))
        self.checkDBRemoveDeleted.setObjectName(_fromUtf8("checkDBRemoveDeleted"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.checkDBRemoveDeleted)
        self.verticalLayout_3.addLayout(self.formLayout_4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.pushButton = QtGui.QPushButton(self.tab_4)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_3.addWidget(self.pushButton)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.comboIsotopeKs.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label_5.setText(_translate("Form", "Ending Slope", None))
        self.label_4.setText(_translate("Form", "Starting Slope", None))
        self.label_6.setText(_translate("Form", "Max Peak Width (min)", None))
        self.label_7.setText(_translate("Form", "Min Peak Height", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Form", "Simple Peak Finder", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("Form", "StatSlope Peak Finder", None))
        self.label_12.setText(_translate("Form", "Minimum Signal-Noise Ratio", None))
        self.label_13.setText(_translate("Form", "Assumed Sigma", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("Form", "Wavelet Peak Finder", None))
        self.label_14.setText(_translate("Form", "Peak Model", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("Form", "LeastSq Integrator", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Peak Finders && Integrators", None))
        self.label.setText(_translate("Form", "Constants", None))
        self.comboIsotopeKs.setItemText(0, _translate("Form", "Craig", None))
        self.comboIsotopeKs.setItemText(1, _translate("Form", "IAEA", None))
        self.comboIsotopeKs.setItemText(2, _translate("Form", "Warner", None))
        self.comboIsotopeKs.setItemText(3, _translate("Form", "Santrock", None))
        self.comboIsotopeKs.setItemText(4, _translate("Form", "Assonov", None))
        self.comboIsotopeKs.setItemText(5, _translate("Form", "Assonov2", None))
        self.comboIsotopeKs.setItemText(6, _translate("Form", "Isodat", None))
        self.label_2.setText(_translate("Form", "Method", None))
        self.comboIsotopeMethod.setItemText(0, _translate("Form", "Santrock-Studley-Hayes", None))
        self.comboIsotopeMethod.setItemText(1, _translate("Form", "Craig", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Isotopes", None))
        self.label_8.setText(_translate("Form", "Compound DB", None))
        self.label_9.setText(_translate("Form", "Method DB", None))
        self.label_10.setText(_translate("Form", "Rescan on Open", None))
        self.label_11.setText(_translate("Form", "Remove Deleted Files", None))
        self.pushButton.setText(_translate("Form", "Copy Settings from Other AstonDB", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Aston", None))

