# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aston.ui'
#
# Created: Wed Nov 28 00:19:38 2012
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(694, 537)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.plotArea = QtGui.QVBoxLayout()
        self.plotArea.setObjectName(_fromUtf8("plotArea"))
        self.verticalLayout.addLayout(self.plotArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 694, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuExport = QtGui.QMenu(self.menuFile)
        self.menuExport.setObjectName(_fromUtf8("menuExport"))
        self.menuIntegrate = QtGui.QMenu(self.menubar)
        self.menuIntegrate.setObjectName(_fromUtf8("menuIntegrate"))
        self.menuSpectrum = QtGui.QMenu(self.menubar)
        self.menuSpectrum.setObjectName(_fromUtf8("menuSpectrum"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setEnabled(False)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuPeaks = QtGui.QMenu(self.menubar)
        self.menuPeaks.setObjectName(_fromUtf8("menuPeaks"))
        self.menuWindows = QtGui.QMenu(self.menubar)
        self.menuWindows.setObjectName(_fromUtf8("menuWindows"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.filesDockWidget = QtGui.QDockWidget(MainWindow)
        self.filesDockWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.filesDockWidget.setFloating(False)
        self.filesDockWidget.setObjectName(_fromUtf8("filesDockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lineEdit = QtGui.QLineEdit(self.dockWidgetContents)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.fileTreeView = QtGui.QTreeView(self.dockWidgetContents)
        self.fileTreeView.setObjectName(_fromUtf8("fileTreeView"))
        self.verticalLayout_4.addWidget(self.fileTreeView)
        self.filesDockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.filesDockWidget)
        self.settingsDockWidget = QtGui.QDockWidget(MainWindow)
        self.settingsDockWidget.setObjectName(_fromUtf8("settingsDockWidget"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.dockWidgetContents_3)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.filterLayout = QtGui.QFormLayout()
        self.filterLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.filterLayout.setObjectName(_fromUtf8("filterLayout"))
        self.horizontalLayout_4.addLayout(self.filterLayout)
        self.settingsDockWidget.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.settingsDockWidget)
        self.spectraDockWidget = QtGui.QDockWidget(MainWindow)
        self.spectraDockWidget.setObjectName(_fromUtf8("spectraDockWidget"))
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName(_fromUtf8("dockWidgetContents_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.dockWidgetContents_5)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.specArea = QtGui.QVBoxLayout()
        self.specArea.setObjectName(_fromUtf8("specArea"))
        self.horizontalLayout_3.addLayout(self.specArea)
        self.spectraDockWidget.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.spectraDockWidget)
        self.methodDockWidget = QtGui.QDockWidget(MainWindow)
        self.methodDockWidget.setEnabled(True)
        self.methodDockWidget.setObjectName(_fromUtf8("methodDockWidget"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.methodTreeView = QtGui.QTreeView(self.dockWidgetContents_2)
        self.methodTreeView.setObjectName(_fromUtf8("methodTreeView"))
        self.verticalLayout_2.addWidget(self.methodTreeView)
        self.methodDockWidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.methodDockWidget)
        self.compoundDockWidget = QtGui.QDockWidget(MainWindow)
        self.compoundDockWidget.setObjectName(_fromUtf8("compoundDockWidget"))
        self.dockWidgetContents_6 = QtGui.QWidget()
        self.dockWidgetContents_6.setObjectName(_fromUtf8("dockWidgetContents_6"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents_6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.compoundTreeView = QtGui.QTreeView(self.dockWidgetContents_6)
        self.compoundTreeView.setObjectName(_fromUtf8("compoundTreeView"))
        self.verticalLayout_3.addWidget(self.compoundTreeView)
        self.compoundDockWidget.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.compoundDockWidget)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionExportChromatogram = QtGui.QAction(MainWindow)
        self.actionExportChromatogram.setObjectName(_fromUtf8("actionExportChromatogram"))
        self.actionChromatogram_as_CSV = QtGui.QAction(MainWindow)
        self.actionChromatogram_as_CSV.setEnabled(False)
        self.actionChromatogram_as_CSV.setObjectName(_fromUtf8("actionChromatogram_as_CSV"))
        self.actionExportSpectra = QtGui.QAction(MainWindow)
        self.actionExportSpectra.setObjectName(_fromUtf8("actionExportSpectra"))
        self.actionSpectra_as_CSV = QtGui.QAction(MainWindow)
        self.actionSpectra_as_CSV.setEnabled(False)
        self.actionSpectra_as_CSV.setObjectName(_fromUtf8("actionSpectra_as_CSV"))
        self.actionExportSelectedItems = QtGui.QAction(MainWindow)
        self.actionExportSelectedItems.setEnabled(True)
        self.actionExportSelectedItems.setObjectName(_fromUtf8("actionExportSelectedItems"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionIntegrate = QtGui.QAction(MainWindow)
        self.actionIntegrate.setObjectName(_fromUtf8("actionIntegrate"))
        self.actionIntegration_Parameters = QtGui.QAction(MainWindow)
        self.actionIntegration_Parameters.setEnabled(False)
        self.actionIntegration_Parameters.setObjectName(_fromUtf8("actionIntegration_Parameters"))
        self.actionIntegrate_2 = QtGui.QAction(MainWindow)
        self.actionIntegrate_2.setEnabled(False)
        self.actionIntegrate_2.setObjectName(_fromUtf8("actionIntegrate_2"))
        self.actionSearch_Database = QtGui.QAction(MainWindow)
        self.actionSearch_Database.setEnabled(False)
        self.actionSearch_Database.setObjectName(_fromUtf8("actionSearch_Database"))
        self.actionSave_to_Database = QtGui.QAction(MainWindow)
        self.actionSave_to_Database.setEnabled(False)
        self.actionSave_to_Database.setObjectName(_fromUtf8("actionSave_to_Database"))
        self.actionSequence = QtGui.QAction(MainWindow)
        self.actionSequence.setEnabled(False)
        self.actionSequence.setObjectName(_fromUtf8("actionSequence"))
        self.actionStructure = QtGui.QAction(MainWindow)
        self.actionStructure.setEnabled(False)
        self.actionStructure.setObjectName(_fromUtf8("actionStructure"))
        self.actionCalculate_Info = QtGui.QAction(MainWindow)
        self.actionCalculate_Info.setObjectName(_fromUtf8("actionCalculate_Info"))
        self.actionAutoAlignChromatogram = QtGui.QAction(MainWindow)
        self.actionAutoAlignChromatogram.setEnabled(False)
        self.actionAutoAlignChromatogram.setObjectName(_fromUtf8("actionAutoAlignChromatogram"))
        self.actionSubtractAddChromatogram = QtGui.QAction(MainWindow)
        self.actionSubtractAddChromatogram.setEnabled(False)
        self.actionSubtractAddChromatogram.setObjectName(_fromUtf8("actionSubtractAddChromatogram"))
        self.actionRevert = QtGui.QAction(MainWindow)
        self.actionRevert.setEnabled(True)
        self.actionRevert.setObjectName(_fromUtf8("actionRevert"))
        self.actionEditFilters = QtGui.QAction(MainWindow)
        self.actionEditFilters.setObjectName(_fromUtf8("actionEditFilters"))
        self.actionSmoothChromatogram = QtGui.QAction(MainWindow)
        self.actionSmoothChromatogram.setObjectName(_fromUtf8("actionSmoothChromatogram"))
        self.actionAlign_Chromatogram = QtGui.QAction(MainWindow)
        self.actionAlign_Chromatogram.setObjectName(_fromUtf8("actionAlign_Chromatogram"))
        self.actionCalculate_Isotopic = QtGui.QAction(MainWindow)
        self.actionCalculate_Isotopic.setEnabled(False)
        self.actionCalculate_Isotopic.setObjectName(_fromUtf8("actionCalculate_Isotopic"))
        self.actionExport_Peak_List = QtGui.QAction(MainWindow)
        self.actionExport_Peak_List.setEnabled(False)
        self.actionExport_Peak_List.setObjectName(_fromUtf8("actionExport_Peak_List"))
        self.actionIdentify = QtGui.QAction(MainWindow)
        self.actionIdentify.setEnabled(False)
        self.actionIdentify.setObjectName(_fromUtf8("actionIdentify"))
        self.actionFiles = QtGui.QAction(MainWindow)
        self.actionFiles.setCheckable(True)
        self.actionFiles.setChecked(True)
        self.actionFiles.setObjectName(_fromUtf8("actionFiles"))
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setCheckable(True)
        self.actionSettings.setChecked(False)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionPeaks = QtGui.QAction(MainWindow)
        self.actionPeaks.setCheckable(True)
        self.actionPeaks.setChecked(True)
        self.actionPeaks.setObjectName(_fromUtf8("actionPeaks"))
        self.actionSpectra = QtGui.QAction(MainWindow)
        self.actionSpectra.setCheckable(True)
        self.actionSpectra.setChecked(True)
        self.actionSpectra.setObjectName(_fromUtf8("actionSpectra"))
        self.actionMethods = QtGui.QAction(MainWindow)
        self.actionMethods.setCheckable(True)
        self.actionMethods.setObjectName(_fromUtf8("actionMethods"))
        self.actionCompounds = QtGui.QAction(MainWindow)
        self.actionCompounds.setCheckable(True)
        self.actionCompounds.setObjectName(_fromUtf8("actionCompounds"))
        self.actionAll_Items_as_CSV = QtGui.QAction(MainWindow)
        self.actionAll_Items_as_CSV.setObjectName(_fromUtf8("actionAll_Items_as_CSV"))
        self.actionGraph_Style = QtGui.QAction(MainWindow)
        self.actionGraph_Style.setObjectName(_fromUtf8("actionGraph_Style"))
        self.actionLegend = QtGui.QAction(MainWindow)
        self.actionLegend.setCheckable(True)
        self.actionLegend.setObjectName(_fromUtf8("actionLegend"))
        self.actionColor_Scheme = QtGui.QAction(MainWindow)
        self.actionColor_Scheme.setObjectName(_fromUtf8("actionColor_Scheme"))
        self.actionPeak_Labels = QtGui.QAction(MainWindow)
        self.actionPeak_Labels.setEnabled(False)
        self.actionPeak_Labels.setObjectName(_fromUtf8("actionPeak_Labels"))
        self.menuExport.addAction(self.actionExportChromatogram)
        self.menuExport.addAction(self.actionExportSpectra)
        self.menuExport.addAction(self.actionExportSelectedItems)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuIntegrate.addAction(self.actionIntegrate)
        self.menuIntegrate.addAction(self.actionIntegrate_2)
        self.menuIntegrate.addAction(self.actionIntegration_Parameters)
        self.menuIntegrate.addSeparator()
        self.menuIntegrate.addAction(self.actionAutoAlignChromatogram)
        self.menuIntegrate.addAction(self.actionSubtractAddChromatogram)
        self.menuIntegrate.addAction(self.actionEditFilters)
        self.menuIntegrate.addAction(self.actionRevert)
        self.menuSpectrum.addAction(self.actionSearch_Database)
        self.menuSpectrum.addAction(self.actionSave_to_Database)
        self.menuSpectrum.addAction(self.actionSequence)
        self.menuSpectrum.addAction(self.actionStructure)
        self.menuPeaks.addAction(self.actionCalculate_Isotopic)
        self.menuPeaks.addAction(self.actionExport_Peak_List)
        self.menuPeaks.addAction(self.actionIdentify)
        self.menuWindows.addAction(self.actionFiles)
        self.menuWindows.addAction(self.actionSettings)
        self.menuWindows.addAction(self.actionSpectra)
        self.menuWindows.addAction(self.actionMethods)
        self.menuWindows.addAction(self.actionCompounds)
        self.menuSettings.addAction(self.actionGraph_Style)
        self.menuSettings.addAction(self.actionLegend)
        self.menuSettings.addAction(self.actionColor_Scheme)
        self.menuSettings.addAction(self.actionPeak_Labels)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuIntegrate.menuAction())
        self.menubar.addAction(self.menuSpectrum.menuAction())
        self.menubar.addAction(self.menuPeaks.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuWindows.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Aston", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExport.setTitle(QtGui.QApplication.translate("MainWindow", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.menuIntegrate.setTitle(QtGui.QApplication.translate("MainWindow", "Chromatogram", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSpectrum.setTitle(QtGui.QApplication.translate("MainWindow", "Spectrum", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPeaks.setTitle(QtGui.QApplication.translate("MainWindow", "Peaks", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWindows.setTitle(QtGui.QApplication.translate("MainWindow", "Windows", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.filesDockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Seach by Name", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsDockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.spectraDockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Spectra", None, QtGui.QApplication.UnicodeUTF8))
        self.methodDockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Methods", None, QtGui.QApplication.UnicodeUTF8))
        self.compoundDockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Compounds", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportChromatogram.setText(QtGui.QApplication.translate("MainWindow", "Visible Chromatogram", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChromatogram_as_CSV.setText(QtGui.QApplication.translate("MainWindow", "Chromatogram as CSV", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportSpectra.setText(QtGui.QApplication.translate("MainWindow", "Visible Spectra", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpectra_as_CSV.setText(QtGui.QApplication.translate("MainWindow", "Spectra as CSV", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportSelectedItems.setText(QtGui.QApplication.translate("MainWindow", "Selected Items", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIntegrate.setText(QtGui.QApplication.translate("MainWindow", "Quick Integrate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIntegration_Parameters.setText(QtGui.QApplication.translate("MainWindow", "Integration Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIntegrate_2.setText(QtGui.QApplication.translate("MainWindow", "Integrate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSearch_Database.setText(QtGui.QApplication.translate("MainWindow", "Search Database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_to_Database.setText(QtGui.QApplication.translate("MainWindow", "Save to Database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSequence.setText(QtGui.QApplication.translate("MainWindow", "Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStructure.setText(QtGui.QApplication.translate("MainWindow", "Structure", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCalculate_Info.setText(QtGui.QApplication.translate("MainWindow", "Calculate Info", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoAlignChromatogram.setText(QtGui.QApplication.translate("MainWindow", "Auto-Align Chromatogram", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSubtractAddChromatogram.setText(QtGui.QApplication.translate("MainWindow", "Subtract/Add Chromatogram", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRevert.setText(QtGui.QApplication.translate("MainWindow", "Revert to Original", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditFilters.setText(QtGui.QApplication.translate("MainWindow", "Edit Filters...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSmoothChromatogram.setText(QtGui.QApplication.translate("MainWindow", "Smooth Chromatogram", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAlign_Chromatogram.setText(QtGui.QApplication.translate("MainWindow", "Adjust Chromatogram", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCalculate_Isotopic.setText(QtGui.QApplication.translate("MainWindow", "Calculate Isotopic", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_Peak_List.setText(QtGui.QApplication.translate("MainWindow", "Export Peak List", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIdentify.setText(QtGui.QApplication.translate("MainWindow", "Quick Identify", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFiles.setText(QtGui.QApplication.translate("MainWindow", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPeaks.setText(QtGui.QApplication.translate("MainWindow", "Peaks", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpectra.setText(QtGui.QApplication.translate("MainWindow", "Spectra", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMethods.setText(QtGui.QApplication.translate("MainWindow", "Methods", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompounds.setText(QtGui.QApplication.translate("MainWindow", "Compounds", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAll_Items_as_CSV.setText(QtGui.QApplication.translate("MainWindow", "All Items as CSV", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGraph_Style.setText(QtGui.QApplication.translate("MainWindow", "Graph Style", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLegend.setText(QtGui.QApplication.translate("MainWindow", "Legend", None, QtGui.QApplication.UnicodeUTF8))
        self.actionColor_Scheme.setText(QtGui.QApplication.translate("MainWindow", "Color Scheme", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPeak_Labels.setText(QtGui.QApplication.translate("MainWindow", "Peak Labels", None, QtGui.QApplication.UnicodeUTF8))

