# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aston_filterwindow.ui'
#
# Created: Sun Nov  6 13:06:14 2011
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_filterDialog(object):
    def setupUi(self, filterDialog):
        filterDialog.setObjectName(_fromUtf8("filterDialog"))
        filterDialog.resize(500, 450)
        filterDialog.setWindowTitle(QtGui.QApplication.translate("filterDialog", "Filter Chromatogram", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout = QtGui.QVBoxLayout(filterDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(filterDialog)
        self.groupBox.setTitle(QtGui.QApplication.translate("filterDialog", "Ions / Wavelengths", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.ionList = QtGui.QListWidget(self.groupBox)
        self.ionList.setObjectName(_fromUtf8("ionList"))
        self.verticalLayout_2.addWidget(self.ionList)
        self.addDefinedIonButton = QtGui.QTabWidget(self.groupBox)
        self.addDefinedIonButton.setElideMode(QtCore.Qt.ElideNone)
        self.addDefinedIonButton.setDocumentMode(True)
        self.addDefinedIonButton.setObjectName(_fromUtf8("addDefinedIonButton"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.definedIonBox = QtGui.QComboBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.definedIonBox.sizePolicy().hasHeightForWidth())
        self.definedIonBox.setSizePolicy(sizePolicy)
        self.definedIonBox.setObjectName(_fromUtf8("definedIonBox"))
        self.horizontalLayout_4.addWidget(self.definedIonBox)
        self.pushButton_4 = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setText(QtGui.QApplication.translate("filterDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.addDefinedIonButton.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.singleIonBox = QtGui.QComboBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.singleIonBox.sizePolicy().hasHeightForWidth())
        self.singleIonBox.setSizePolicy(sizePolicy)
        self.singleIonBox.setEditable(True)
        self.singleIonBox.setObjectName(_fromUtf8("singleIonBox"))
        self.horizontalLayout_2.addWidget(self.singleIonBox)
        self.addSingleIonButton = QtGui.QPushButton(self.tab_2)
        self.addSingleIonButton.setText(QtGui.QApplication.translate("filterDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.addSingleIonButton.setObjectName(_fromUtf8("addSingleIonButton"))
        self.horizontalLayout_2.addWidget(self.addSingleIonButton)
        self.addDefinedIonButton.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.startRangeIonBox = QtGui.QSpinBox(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startRangeIonBox.sizePolicy().hasHeightForWidth())
        self.startRangeIonBox.setSizePolicy(sizePolicy)
        self.startRangeIonBox.setObjectName(_fromUtf8("startRangeIonBox"))
        self.horizontalLayout_3.addWidget(self.startRangeIonBox)
        self.label_8 = QtGui.QLabel(self.tab_3)
        self.label_8.setMaximumSize(QtCore.QSize(20, 20))
        self.label_8.setText(QtGui.QApplication.translate("filterDialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(False)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_3.addWidget(self.label_8)
        self.endRangeIonBox = QtGui.QSpinBox(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endRangeIonBox.sizePolicy().hasHeightForWidth())
        self.endRangeIonBox.setSizePolicy(sizePolicy)
        self.endRangeIonBox.setObjectName(_fromUtf8("endRangeIonBox"))
        self.horizontalLayout_3.addWidget(self.endRangeIonBox)
        self.addRangeIonButton = QtGui.QPushButton(self.tab_3)
        self.addRangeIonButton.setText(QtGui.QApplication.translate("filterDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.addRangeIonButton.setObjectName(_fromUtf8("addRangeIonButton"))
        self.horizontalLayout_3.addWidget(self.addRangeIonButton)
        self.addDefinedIonButton.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.userIonBox = QtGui.QLineEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userIonBox.sizePolicy().hasHeightForWidth())
        self.userIonBox.setSizePolicy(sizePolicy)
        self.userIonBox.setObjectName(_fromUtf8("userIonBox"))
        self.horizontalLayout.addWidget(self.userIonBox)
        self.addUserIonButton = QtGui.QPushButton(self.tab_4)
        self.addUserIonButton.setText(QtGui.QApplication.translate("filterDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.addUserIonButton.setObjectName(_fromUtf8("addUserIonButton"))
        self.horizontalLayout.addWidget(self.addUserIonButton)
        self.addDefinedIonButton.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.addDefinedIonButton)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(filterDialog)
        self.groupBox_3.setTitle(QtGui.QApplication.translate("filterDialog", "Offset && Scaling", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.XOffsetBox = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.XOffsetBox.setMinimum(-1000.0)
        self.XOffsetBox.setMaximum(1000.0)
        self.XOffsetBox.setObjectName(_fromUtf8("XOffsetBox"))
        self.gridLayout.addWidget(self.XOffsetBox, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setText(QtGui.QApplication.translate("filterDialog", "Y Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.YOffsetBox = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.YOffsetBox.setMinimum(-10000.0)
        self.YOffsetBox.setMaximum(10000.0)
        self.YOffsetBox.setObjectName(_fromUtf8("YOffsetBox"))
        self.gridLayout.addWidget(self.YOffsetBox, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setText(QtGui.QApplication.translate("filterDialog", "X Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setText(QtGui.QApplication.translate("filterDialog", "Y Scaling", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.YScaleBox = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.YScaleBox.setMinimum(-1000.0)
        self.YScaleBox.setMaximum(1000.0)
        self.YScaleBox.setProperty("value", 1.0)
        self.YScaleBox.setObjectName(_fromUtf8("YScaleBox"))
        self.gridLayout.addWidget(self.YScaleBox, 1, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setText(QtGui.QApplication.translate("filterDialog", "X Scaling", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.XScaleBox = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.XScaleBox.setMinimum(-1000.0)
        self.XScaleBox.setMaximum(1000.0)
        self.XScaleBox.setProperty("value", 1.0)
        self.XScaleBox.setObjectName(_fromUtf8("XScaleBox"))
        self.gridLayout.addWidget(self.XScaleBox, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.groupBox_4 = QtGui.QGroupBox(filterDialog)
        self.groupBox_4.setTitle(QtGui.QApplication.translate("filterDialog", "Noise Removal", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_9 = QtGui.QLabel(self.groupBox_4)
        self.label_9.setEnabled(False)
        self.label_9.setText(QtGui.QApplication.translate("filterDialog", "Not Yet Implemented", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_5.addWidget(self.label_9)
        self.horizontalLayout_6.addWidget(self.groupBox_4)
        self.groupBox_2 = QtGui.QGroupBox(filterDialog)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("filterDialog", "Smoothing", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setText(QtGui.QApplication.translate("filterDialog", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.smoothComboBox = QtGui.QComboBox(self.groupBox_2)
        self.smoothComboBox.setObjectName(_fromUtf8("smoothComboBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.smoothComboBox)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setText(QtGui.QApplication.translate("filterDialog", "Window", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.smoothWindowBox = QtGui.QSpinBox(self.groupBox_2)
        self.smoothWindowBox.setMinimum(1)
        self.smoothWindowBox.setProperty("value", 5)
        self.smoothWindowBox.setObjectName(_fromUtf8("smoothWindowBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.smoothWindowBox)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setText(QtGui.QApplication.translate("filterDialog", "Order", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.smoothOrderBox = QtGui.QSpinBox(self.groupBox_2)
        self.smoothOrderBox.setMinimum(1)
        self.smoothOrderBox.setObjectName(_fromUtf8("smoothOrderBox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.smoothOrderBox)
        self.horizontalLayout_6.addWidget(self.groupBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.buttonBox = QtGui.QDialogButtonBox(filterDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(filterDialog)
        self.addDefinedIonButton.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), filterDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), filterDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(filterDialog)

    def retranslateUi(self, filterDialog):
        self.addDefinedIonButton.setTabText(self.addDefinedIonButton.indexOf(self.tab), QtGui.QApplication.translate("filterDialog", "Defined", None, QtGui.QApplication.UnicodeUTF8))
        self.addDefinedIonButton.setTabText(self.addDefinedIonButton.indexOf(self.tab_2), QtGui.QApplication.translate("filterDialog", "Single", None, QtGui.QApplication.UnicodeUTF8))
        self.addDefinedIonButton.setTabText(self.addDefinedIonButton.indexOf(self.tab_3), QtGui.QApplication.translate("filterDialog", "Range", None, QtGui.QApplication.UnicodeUTF8))
        self.addDefinedIonButton.setTabText(self.addDefinedIonButton.indexOf(self.tab_4), QtGui.QApplication.translate("filterDialog", "User", None, QtGui.QApplication.UnicodeUTF8))

